# Generated by Django 4.2.1 on 2023-05-29 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
