# Generated by Django 4.2.1 on 2023-06-20 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feria', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsletter',
            options={'verbose_name': 'Lista de suscriptores', 'verbose_name_plural': 'Lista de suscriptores'},
        ),
    ]
