# Generated by Django 4.2.1 on 2023-06-03 02:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feria', '0002_remove_client_lastname_client_avatar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='classification',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5)]),
        ),
    ]
