# Generated by Django 4.2.1 on 2023-06-03 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feria', '0003_review_classification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='description',
            field=models.CharField(max_length=140),
        ),
    ]
